### ISSUE TITLE
Use with Medical Dictionary

### ISSUE THREAD

**Issue by PMcManus09** [z1lc/AutoDefine#14]
Is there any way to get the add on to work with the use of Merriam Webster Medical dictionary? 

Not sure if this is the correct place for this. Thanks in advance!

**Comment by z1lc** [comment]
This should be relatively straightforward because Merriam Webster [provides an API](https://www.dictionaryapi.com/products/api-medical-dictionary.htm) for the medical dictionary that is very similar to the collegiate one AutoDefine already uses. That said, it does require you to register for a separate medical API key. I'll take a stab at it.

**Comment by PMcManus09** [comment]
Appreciate it, I have been playing around with using the different API and web address but couldn't get it to work. Thanks!

**Comment by z1lc** [comment]
I've implemented the Medical Dictionary functionality in cf31ffa3d5a5067e8b74652e5f99f3129c99b5ea.

Since the medical API and the collegiate API sometimes have overlapping definitions for the same word, I've chosen to also add a setting in preferences where you can select usage of the collegiate or medical dictionaries.

Please update AutoDefine within Anki and let me know if this works for you. If you find bugs, please open separate issue(s).
